name: Beyond The Sky Films
favicon: null
layout_spectrum: 0.12329
typography_spectrum: 0.37165
title: Beyond The Sky Films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#373737'
    - '#fdfdfd'
    - '#8d8d8d'
    - '#5f5f5f'
    - '#c3c3c3'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
