name: Beyond The Sky Films
favicon: null
layout_spectrum: 0
typography_spectrum: 0.37165
title: Beyond The Sky Films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313131'
    - '#f4f4f4'
    - '#d9d9d9'
    - '#a5a5a5'
    - '#6b6b6b'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
