name: Beyond The Sky Films
favicon: null
layout_spectrum: 0.51157
typography_spectrum: 0.08569
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8125411046203226
  lightness: 0.06940391566604376
  saturation: 0.45097226230427623
  rhythmicContrast: 0.7963797121774405
purpose: []
